FROM nginx:alpine

# Set NODE_ENV to production
ENV NODE_ENV production

# Copy built assets from builder'
COPY ./build/ /usr/share/nginx/html

# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
