on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        - name: Setup environments
          run: |
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env
            echo "REACT_APP_API_VERSION=${{ secrets.REACT_APP_API_VERSION }}" >> .env
            echo "PUBLIC_URL=${{ secrets.PUBLIC_URL }}" >> .env
            echo "MSAL_CLIENT_ID=${{ secrets.MSAL_CLIENT_ID }}" >> .env
            echo "MSAL_AUTHORITY_TENANT_ID=${{ secrets.MSAL_AUTHORITY_TENANT_ID }}" >> .env
            echo "MSAL_AUTHORITY_POLICY=${{ secrets.MSAL_AUTHORITY_POLICY }}" >> .env
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sa${{ secrets.ACR_REPOSITORY }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.ACR_REPOSITORY }}:${{ github.sha }}